### ISSUE TITLE
Improper key check in dicitonary

### ISSUE THREAD

**Issue by H4NM** [H4NM/WhoYouCalling#5]
When supplying other executables that are not added as tracked child processes with the `-x` flag there's an assumption they're included within `s_collectiveProcessInfo`. This needs to be reworked, not just to fix the issue but also to support the possibility of monitoring *all* processes on a windows host. Process starts with provided additional executables causes WhoYouCalling to crash. 

```batch
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key '5560' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at WhoYouCalling.Program.CatalogETWActivity(String executable, String execAction, String execObject, String execObjectCommandLine, Int32 execPID, Int32 parentExecPID, EventType eventType, ConnectionRecord connectionRecord, DNSResponse dnsResponse, DNSQuery dnsQuery) in WhoYouCalling\Program.cs:line 638
   at WhoYouCalling.ETW.KernelListener.childProcessStarted(ProcessTraceData data) in WhoYouCalling\ETW\KernelListener.cs:line 117
   at Microsoft.Diagnostics.Tracing.ETWTraceEventSource.RawDispatch(EVENT_RECORD* rawData)
   at Microsoft.Diagnostics.Tracing.TraceEventNativeMethods.ProcessTrace(UInt64[] handleArray, UInt32 handleCount, IntPtr StartTime, IntPtr EndTime)
   at Microsoft.Diagnostics.Tracing.TraceEventNativeMethods.ProcessTrace(SafeTraceHandle[] handleArray, IntPtr StartTime, IntPtr EndTime)
   at Microsoft.Diagnostics.Tracing.ETWTraceEventSource.ProcessOneFile()
   at Microsoft.Diagnostics.Tracing.ETWTraceEventSource.Process()
   at WhoYouCalling.ETW.KernelListener.Listen() in WhoYouCalling\ETW\KernelListener.cs:line 37
   at WhoYouCalling.Program.<>c.<Main>b__20_0() in WhoYouCalling\Program.cs:line 123
```

This is a priority to fix before releasing 1.2. The issue still got into the main branch so self compiling WhoYouCalling is the only way to encounter this at the moment.

**Comment by H4NM** [comment]
Fixed with https://github.com/H4NM/WhoYouCalling/commit/468b14796feb2e1d7066356822a1acc3c5ef3aa3
